---
galaxy_info:
  author: 
  description: LUKS disk encryption role
  company: 
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - "bionic"
        - "focal"
        - "jammy"
dependencies: []
